import { Language } from './types';

export const CATEGORIES = ['Work', 'Personal', 'Study', 'Health', 'Finance', 'Other'] as const;

export const QUOTES = [
  "The secret of getting ahead is getting started.",
  "Focus on being productive instead of busy.",
  "Small steps lead to big changes.",
  "Don't wait. The time will never be just right.",
  "Act as if what you do makes a difference. It does."
];

export const TRANSLATIONS = {
  en: {
    welcome: "Welcome to Collab Task",
    login: "Log In",
    register: "Register",
    email: "Email",
    password: "Password",
    username: "Username",
    bio: "Bio",
    tasks: "Tasks",
    settings: "Settings",
    logout: "Log Out",
    addTask: "Add Task",
    editTask: "Edit Task",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    completed: "Completed",
    pending: "Pending",
    aiAssistant: "AI Assistant",
    aiPromptPlaceholder: "e.g., Make a 3-day study plan for React...",
    generate: "Generate",
    profile: "Profile",
    appearance: "Appearance",
    language: "Language",
    english: "English",
    myanmar: "Myanmar (Unicode)",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    about: "About",
    poweredBy: "Powered by CodeCollab Technology",
    search: "Search tasks...",
    filter: "Filter",
    all: "All",
    low: "Low",
    medium: "Medium",
    high: "High",
    due: "Due",
    export: "Export to TXT",
    backup: "Backup Data",
    onboardingTitle: "Organize your life with AI",
    onboardingDesc: "Smart task management powered by Collab AI to help you achieve more.",
    getStarted: "Get Started",
    notifications: "Notifications",
    version: "Version 1.0.0",
    confirmDelete: "Are you sure you want to delete this?",
    taskTitle: "Task Title",
    taskDesc: "Description (Optional)",
    verifyEmailTitle: "Verify your email",
    verifyEmailDesc: "We've sent a verification link to your email. Please click the link to verify your account.",
    resendEmail: "Resend Verification Email",
    iHaveVerified: "I have verified",
    emailNotVerified: "Email not verified. Please check your inbox.",
  },
  mm: {
    welcome: "Collab Task မှ ကြိုဆိုပါသည်",
    login: "အကောင့်ဝင်ရန်",
    register: "အကောင့်သစ်ဖွင့်ရန်",
    email: "အီးမေးလ်",
    password: "စကားဝှက်",
    username: "အသုံးပြုသူအမည်",
    bio: "အကျဉ်းချုပ်",
    tasks: "လုပ်ဆောင်ရန်များ",
    settings: "ဆက်တင်များ",
    logout: "ထွက်ရန်",
    addTask: "အသစ်ထည့်ရန်",
    editTask: "ပြင်ဆင်ရန်",
    delete: "ဖျက်ရန်",
    save: "သိမ်းဆည်းရန်",
    cancel: "မလုပ်တော့ပါ",
    completed: "ပြီးစီး",
    pending: "မပြီးသေး",
    aiAssistant: "AI အကူအညီ",
    aiPromptPlaceholder: "ဥပမာ - ၃ ရက်စာ စာလေ့လာမည့်အချိန်ဇယား ဆွဲပေးပါ...",
    generate: "ဖန်တီးပါ",
    profile: "ပရိုဖိုင်",
    appearance: "အသွင်အပြင်",
    language: "ဘာသာစကား",
    english: "အင်္ဂလိပ်",
    myanmar: "မြန်မာ (ယူနီကုဒ်)",
    darkMode: "အမှောင်မုဒ်",
    lightMode: "အလင်းမုဒ်",
    about: "အကြောင်းအရာ",
    poweredBy: "CodeCollab Technology မှ စွမ်းအားမြှင့်တင်ထားသည်",
    search: "ရှာဖွေရန်...",
    filter: "စစ်ထုတ်ရန်",
    all: "အားလုံး",
    low: "နိမ့်",
    medium: "ပုံမှန်",
    high: "မြင့်",
    due: "သတ်မှတ်ရက်",
    export: "TXT ထုတ်ရန်",
    backup: "ဒေတာသိမ်းရန်",
    onboardingTitle: "AI ဖြင့် ဘဝကို စနစ်တကျစီမံပါ",
    onboardingDesc: "Collab AI နည်းပညာဖြင့် သင့်လုပ်ငန်းများကို ပိုမိုထိရောက်စွာ ဆောင်ရွက်နိုင်ပါပြီ။",
    getStarted: "စတင်ရန်",
    notifications: "အသိပေးချက်များ",
    version: "ဗားရှင်း ၁.၀.၀",
    confirmDelete: "ဖျက်မည်မှာ သေချာပါသလား?",
    taskTitle: "ခေါင်းစဉ်",
    taskDesc: "အကြောင်းအရာ (ရှိလျှင်)",
    verifyEmailTitle: "အီးမေးလ် အတည်ပြုပါ",
    verifyEmailDesc: "သင့်အီးမေးလ်သို့ အတည်ပြုလင့်ခ် ပေးပို့ထားပါသည်။ ကျေးဇူးပြု၍ စစ်ဆေးပါ။",
    resendEmail: "အီးမေးလ် ပြန်ပို့ရန်",
    iHaveVerified: "အတည်ပြုပြီးပါပြီ",
    emailNotVerified: "အီးမေးလ် အတည်ပြုခြင်း မအောင်မြင်သေးပါ။",
  }
};

export const getTranslation = (lang: Language, key: keyof typeof TRANSLATIONS['en']) => {
  return TRANSLATIONS[lang][key] || TRANSLATIONS['en'][key];
};